set -g mouse on

# KEYBINDINGS
unbind-key !
unbind-key \"
unbind-key \%

bind S-Down split-window -vc "#{pane_current_path}"
bind S-Right split-window -hc "#{pane_current_path}"
bind S-Up split-window -vc "#{pane_current_path}"\; swap-pane -d -t -1
bind S-Left split-window -hc "#{pane_current_path}"\; swap-pane -d -t -1
bind C-b selectp -t "{next}" # Vim like panes
bind-key -r -T prefix M-Up resize-pane -U 5
bind-key -r -T prefix M-Down resize-pane -D 5
bind-key -r -T prefix M-Left resize-pane -L 5
bind-key -r -T prefix M-Right resize-pane -U 5

bind q killp

# Vi mode for copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

# DESIGN TWEAKS
set -g default-terminal "screen-256color"

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=brightred bold'

# panes
set -g pane-border-style 'fg=white'
set -g pane-active-border-style 'fg=brightred'
set -g pane-border-lines single
set -g pane-border-status top
set -g pane-border-format "[ #P #T ]"

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=brightred'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black'
# Show "PREFIX" when the prefix has been pressed. Show time after
set -g status-right '#{?client_prefix,#[bg=brightgreen] PREFIX ,}#[bg=default] #[fg=brightred] %Y-%m-%d %H:%M [#P] '
set -g status-right-length 50

setw -g window-status-current-style 'bg=brightred fg=black'
setw -g window-status-current-format ' #I #W '
setw -g window-status-style 'fg=brightred bg=black'
setw -g window-status-format ' #I #[fg=white]#W '

setw -g window-status-separator " "

setw -g window-status-bell-style 'fg=yellow bg=brightred bold'

setw -g automatic-rename on
# Automatically name the window after the current path in the currently active pane
# in the window, as well as the running command (if any)
set -g automatic-rename-format '#{b:pane_current_path}#{?#{m/r:(bash|zsh|fish|sh),#{pane_current_command}},, | #{=10:pane_current_command}}'


# messages
set -g message-style 'fg=black bg=brightred bold'

